$schema: https://railway.app/railway.schema.json

services:
  backend:
    build: .
    dockerfile: Dockerfile.backend
    ports:
      - 8000:8000
    healthcheck:
      path: /health
      interval: 30s
      timeout: 10s
      retries: 3
    restart_policy:
      condition: on_failure
      max_retries: 10
    environment:
      - NODE_ENV=production
      - PORT=8000
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=careerpath
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${{POSTGRES_PASSWORD}}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: